server:
    port: 8081
spring:
  application:
    name: product service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/db-oauth-gateway
    username: lyzhia
    password: 123456
#JPA config
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  prometheus:
    metrics:
      export:
        enabled: true



