version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus  # Ensure the prometheus.yml file is here
    command: --config.file=/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:7.5.6
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:
